### ISSUE TITLE
從1.8版升級到2.0版，是否維持登入狀態，愛心資料都沒有遺失，如有問題請在這回報

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-ios#10]

**Comment by Kila888** [comment]
從1.8版升級到2.0版，有維持登入狀態，愛心資料都沒有遺失。

iPad Air 4
Ios14.7.1

**Comment by mingzhen2020** [comment]
9/9測試：正常
ios:14.7

**Comment by Mina5632** [comment]
升級後資料都沒有遺失

iPad Air3
版本14.5.1

**Comment by hualien733** [comment]
9/11 測試

測試正常：維持登入狀態，且愛心資料沒有遺失。

iphone 7 plus
ios 14.7.1

**Comment by Tweetywang** [comment]
測試ok
型號：iPhone XS
iOS:14.7.1

**Comment by Emmayoung1** [comment]
9/11

皆正常。

目前版本2.0(80)

各版本(都有升級通知)都會自動升級，全部已下載資料和愛心資料都在，並維持登入狀態。

iphone 11
IOS14.7.1

**Comment by yiyiherher** [comment]
維持登入
愛心沒有遺失

iphone 8 plus
ios 14.7.1
