### ISSUE TITLE
同帳號的愛心可否正常再多個設備間同步，例如iPhone，iPad，還有Android(打開App的瞬間才會從雲端下載）

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-ios#11]

**Comment by Kila888** [comment]
iPad air4  和 iPhone 11 都下載app且都登同個帳號，兩邊的愛心沒有同步。

**Comment by Emily2392** [comment]
-測試日期：2021/9/10
-測試環境：iPAD Air2/iOS: 14.6
                    iPhone X/iOS: 14.7.1
-測試說明：A. 同帳號的愛心，在另一個帳號由別的情境進入後，會同步出現。
                    B. 同帳號的愛心，如果在兩個APP同時打開運作的狀況，第二個 device不會出現愛心
-Comment: 正常操作情境大部分會出現A情境，因此個人認為是正常

**Comment by totality-of-life** [comment]
這個功能如果同時打開兩個設備A跟B，如果Ａ，Ｂ的愛心有更動，會以最後一個更動的設備的“全部愛心的情況”為主，沒有聰明到記錄單個音檔的最新的愛心情況。

簡單講就是哪個設備的資料最新，就以那個設備為準。

備份愛心是這個功能最主要的目的，簡單的同步算是一個附加功能。

應該不多人要同時在兩個設備上面加愛心吧？
如果我想錯了可以跟我說

**Comment by Emily2392** [comment]
同意，就是這樣。
所以是情境A才是正常情形，判定正常 :-)
