### ISSUE TITLE
影片播放中，切換不同音訊裝置，播放的螢幕會不見

### ISSUE THREAD

**Issue by Lotusho** [totality-of-life/testing-ios#16]
iPhone 11
iOS 14.7.1
說明：影片播放中，切換不同的音訊裝置，如藍芽耳機改成藍芽喇叭，或藍芽喇叭換成手機擴音，螢幕會不見，但音聲仍持續播放。此時，切換成全螢幕，全螢幕會出現。關閉全螢幕，回到資料夾螢幕還是沒有出現。

**Comment by totality-of-life** [comment]
我自己測試沒有問題，你可以試著重開機一次再試試看嗎？
我是從這個介面切換的，不知道跟你一不一樣
![IMG_1932](https://user-images.githubusercontent.com/72474898/132811641-6bbeb6d4-4b77-4258-a6b1-a25567e505ff.PNG)

iPhone SE2
iOS 14.7.1

**Comment by Emily2392** [comment]
我沒問題，由螢幕播放，接手機藍芽。正常
iPAD Air 2 / iOS 14.6
iPhone X / iOS 14.7.1
藍芽耳機: JBL 215 BT

**Comment by Lotusho** [comment]
關機後重開機，重開APP，還是一樣，切換音訊裝置，螢幕會不見。

**Comment by totality-of-life** [comment]
我明白你的意思了，我今天也有遇到
這個我剛剛送出的2.0(79)版有修正這個問題，請去Testflight安裝79版，再試一次看看有修好嗎，謝謝

**Comment by Lotusho** [comment]
有喔～可以了，切換音訊裝置螢幕還在，謝謝。
