### ISSUE TITLE
後台有新檔案案時, 須退回"全部生命"首頁再進入才會更新在"雲端"分頁裡

### ISSUE THREAD

**Issue by alfredoyang** [totality-of-life/testing-ios#19]
1. 進入"全部生命"裡的任一課程, 例如“沒有路的路”
2. 後台新增檔案
3. 在“沒有路的路”頁面裡直接選入“雲端”分頁
4. 沒有發現新檔案
5. 退出“沒有路的路”回到"全部生命"首頁
6. 再次進入“沒有路的路”課程
7. 進入“雲端”分頁, 此時才發現有新增檔案

建議進入雲端分頁時, 能重新從後台再更新一下資料

**Comment by alfredoyang** [comment]
IPhone 12 mini
IOS 14.7.1

**Comment by totality-of-life** [comment]
這件事會等到下一個版本，當初考量不要在正在播放的時候更動播放列表，避免當機。
其實共修是非常特殊的時期，哪有專輯一天更新三次的啦。
之後穩定下來其實只有偶爾上架一個新作品才會變，不過還是可以試試看，謝謝你的建議

**Comment by Kila888** [comment]
3Q very much Andy
