### ISSUE TITLE
全螢幕播放影片時，在右上角音量調整處調小音量，有機率閃一下平時下拉螢幕會出現的訊息通知

### ISSUE THREAD

**Issue by yiyiherher** [totality-of-life/testing-ios#21]
iPhone 8 plus , OS14.7.1

20s測試影片如下
https://drive.google.com/file/d/1fuG57DnnY8cDFfed5ysKgPfnLjUAlT84/view?usp=sharing

若在全螢幕下在右上角音量區調小音量，螢幕會變白，然後最上方出現一個訊息通知的上半部份（平時從螢幕上緣下拉時看到的第一個，以我手機為例是勿擾模式說明。）
只會閃一下，之後就會回到原本的影片正常播放。
也不是每次調小音量都會發生。

**Comment by totality-of-life** [comment]
感謝回報這個問題。
我目前猜測不是條音量造成，而是觸發下拉造成的，我想想看要怎麼處理。

**Comment by totality-of-life** [comment]
85版以後應該修好了
