### ISSUE TITLE
多國語言支援，在帳號頁可以選擇語言（ 繁體中文、簡體中文、English）

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-ios#22]
目前只有支援專輯名稱，歌曲及影片名稱
使用者介面跟錯誤訊息的文字因為比較多地方要改，如果這一版來不及，就等到下一版
讀書會當初只有中文的標題，如果未來博士給了英文標題會補上
兩次共修的每個音檔的英文標題是博士親自取的，推薦大家有興趣可以看看，說不會有什麼啟發

**Comment by coolbil** [comment]
除讀書會外 皆可正常呈現英文、簡體中文標題
iPhone 7
iOS 14.7.1

**Comment by Emily2392** [comment]
切換語言(繁體、簡體、英文)選項後，專輯名稱，歌曲及影片名稱馬上跟著改變 (除了讀書會)，測試正常

iPhone X / 14.7.1
iPAD Air2 / 14.7.1

**Comment by Emmayoung1** [comment]
正常

切換語言選項(繁體、英文、簡體)後，除了讀書會之外，專輯名稱、音檔和影片的標題都有跟著切換，原來在播放的音頻也會停在暫停的秒數，可以繼續接著播放。

iPhone 11
iOS 14.7.1

**Comment by mingzhen2020** [comment]
-測試日期：2021/9/15
-測試結果：選英文語言後，「讀書會、最新消息」兩單元標題維持是中文，其他單元的標題都改成英文。
-測試環境：iphone7/ios14.7

**Comment by Julian8153** [comment]
切換簡中及英文影片標題及檔名都一併切換了，唯有讀書會檔名有切換成簡中但沒切換成英文。

iPhone XR
iOS 14.7.1

**Comment by totality-of-life** [comment]
讀書會當初博士沒有給英文名稱，所以只有中文跟簡體中文

**Comment by yiyiherher** [comment]
專輯名稱，歌曲及影片名稱 英文 簡中 正常

iPhone 8 plus
iOS 14.7.1

**Comment by hualien733** [comment]
[專輯名稱，歌曲及影片名稱] 英文與簡中切換都正常。

iPhone 7 plus
iOS 14.7.1

ps. 如果需要人手幫忙做英文校對或修改，我可以幫忙！tykao1202 at gmail.com

**Comment by totality-of-life** [comment]
現在最新版本(85)，已經完成所有介面的多國語言，如果有興趣的人可以幫忙看看有沒有覺得文字不通順或是帶入錯翻譯的地方，謝謝大家幫忙

**Comment by Emily2392** [comment]
1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。==> 謝謝，辛苦了。
2. 多國語言包括連UI的部分都翻譯完成 ==> 我沒有檢查翻譯，只檢查操作，操作測試，正常。
3. 播放音檔的列表，進入的時候，在本機，會自動滑動至上次最後播放的檔案位置，在雲端，會自動滑到最下面。==> 如題，操作測試，正常
4. 主頁帳號跟最新消息都改成圖示，帳號移動到左邊去，最新消息在右邊。盡可能避免字體條大的時候把帳號功能擠出螢幕，造成使用者找不到帳號頁。==> 如題，操作測試，正常
5. Chromecast 狀抗 ==> 謝謝解釋，收到。沒問題，一切都剛剛好。

iX 10 / 14.8

**Comment by Mina5632** [comment]
切換語言功能測試結果可正常切換

測試版本iPad Air第三代
14.8

**Comment by Julian8153** [comment]
1、使用者介面，簡中、英文正常顯示。
2、播放音檔，本機再次開啟回到上次播放位置；雲端自動滑到最下方。以上都正常。
3、帳號圖示左邊，最新消息右邊都正常，但不會調字體大小故無測試。
iPhone XR 
iOS 14.7.1

**Comment by Kila888** [comment]
1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。>thanks 
2. 多國語言包括連UI的部分都翻譯完成> 可順利切換
3. 播放音檔的列表，進入的時候，在本機，會自動滑動至上次最後播放的檔案位置，在雲端，會自動滑到最下面。》正常
4. 主頁帳號跟最新消息都改成圖示，帳號移動到左邊去，最新消息在右邊。盡可能避免字體條大的時候把帳號功能擠出螢幕，造成使用者找不到帳號頁。 》正常

謝謝你們
IPad Air 4
iOS 14.7.1

**Comment by Mina5632** [comment]
就補充資料夾中無法存在其他語言文字，只有繁體字喔！ ![image](https://user-images.githubusercontent.com/90369794/135049308-fe673870-bd8e-4540-97e7-34cb7caf71ec.png)

**Comment by Mina5632** [comment]
目前共修《沒有路的路》使用上愈到共修時間後段每天都得不停的往下滑頁面，這個動作說來是小問題，但是若能顛倒過來，後下載的位置在最上層，可以省掉不停的滑啊滑～

**Comment by totality-of-life** [comment]
> 目前共修《沒有路的路》使用上愈到共修時間後段每天都得不停的往下滑頁面，這個動作說來是小問題，但是若能顛倒過來，後下載的位置在最上層，可以省掉不停的滑啊滑～

有更新到最新的版本嗎？
最新版本會自動滑到 本機->上次播放的音檔 ，雲端-> 最下面

**Comment by totality-of-life** [comment]
> 就補充資料夾中無法存在其他語言文字，只有繁體字喔！ ![image](https://user-images.githubusercontent.com/90369794/135049308-fe673870-bd8e-4540-97e7-34cb7caf71ec.png)

這是正常的，那邊是用來放youtube博士額外錄的補充說明，還有一些專輯的小冊子，都只有繁體中文，所以這邊也沒有預留三個語言的翻譯

**Comment by Mina5632** [comment]
嗯，有看到了。
