### ISSUE TITLE
課程標題和次標題

### ISSUE THREAD

**Issue by wjwen2021** [totality-of-life/testing-ios#25]
課程次標題及分類在部分機型系統無法顯示，如圖：
Ipad 2018/14.7.1 無法顯示
iPhone SE2/14.7.1 可顯示

![06B45A00-1346-4BAA-9A7A-0B5BA03BEBFF](https://user-images.githubusercontent.com/90315489/135389331-ad84801a-85fb-4c74-899b-7dbc8f2aefc6.jpeg)
![C90BEE31-5A9E-4F5D-8759-F3637A2B1F8B](https://user-images.githubusercontent.com/90315489/135389345-cc62751c-3c70-4228-90f9-1f4349638da8.jpeg)

**Comment by totality-of-life** [comment]
這可能是ipad app沒有更新到最新版，請再試試看。我建議把自動更新打開。

**Comment by wjwen2021** [comment]
是的，my fault. Thank you.
