### ISSUE TITLE
2.1版，Airpods pro 播放問題

### ISSUE THREAD

**Issue by jonsonnee** [totality-of-life/testing-ios#26]
打開App2.2測試版本後
狀況還是與先前e-mail中回覆ㄧ樣
需要再按一次播放鍵
會重頭讀秒後才正常播放

**Comment by totality-of-life** [comment]
感謝回報，我先整理你在email中描述的情況記錄下來，發生的可能原因我還要再想想
--
我的手機iphone 8 plus  ios15  耳機AirPods Pro
昨天清晨更新全部生命app 至2.1後
戴上耳機打開APP點按要聽的檔案 紅框1
![unnamed](https://user-images.githubusercontent.com/72474898/139519075-195ef25e-9f16-4acd-b3fe-289d45c964a7.jpg)
發現沒有聲音但是左下繼續跑秒 紅框2
後來我發現只要按暫停鍵 紅框3
再按一次播放鍵(同樣紅框3)
左下方時間會重原來暫停的時間點跳回0:00重新跑秒 紅框2
然後就有聲音了

試了很多方式
包括點選不同檔案、手機關機重開、耳機重新連結藍芽
結果都一樣

但是
我換了有線耳機、其他品牌藍芽耳機都正常
我的AirPods Pro連到家人的IPHONE 12 (也有裝全部生命app) 也正常

唯獨我的iphone 8 plus 與AirPods Pro
而且只在更新2.1的全部生命app中有上述問題
其他可以撥放音檔的app也正常

大概狀況是這樣
希望只是我個人的特例...
也許將來再更新後就正常了

**Comment by jonsonnee** [comment]
Andy 您好

我用iPhone螢幕錄製了操作的過程
點下去D55後
播放了20秒都沒有聲音
按暫停再按播放後
重新讀秒就有聲音了

您可以看一下影片

謝謝





從我的iPhone傳送

**Comment by totality-of-life** [comment]
影片好像沒有上傳到？

**Comment by totality-of-life** [comment]
我剛把你設定到一個特殊的群組，放了2.0版給你抓，你在Testflight現在應該可以抓到2.0版。如果沒有出現，殺掉app再進去TestFlight抓看看。
試試看真的2.0就不會出現問題了嗎？

**Comment by jonsonnee** [comment]
再傳一次影片看看



從我的iPhone傳送

**Comment by totality-of-life** [comment]
你可能要用網頁操作上傳影片才可以，用email回信給github應該只有文字

**Comment by jonsonnee** [comment]
我裝了2.0就正常了耶


從我的iPhone傳送

**Comment by totality-of-life** [comment]
大概三分鐘後，請你再幫我從TestFlight中裝 2.2 (100)試試看，我想確認另一件事，謝謝

**Comment by jonsonnee** [comment]
這個版本還是不行喔

從我的iPhone傳送

**Comment by totality-of-life** [comment]
好，那我把這版本移除，你現在應該可以裝2.0使用，目前暫時先這樣。
我去比對一下，2.0跟現在的程式碼的差別，哪邊有可能造成這個現象。

2.0  最低ios限制我設定14.5
2.1   最低ios限制我設定14.0  從這邊開始你回報有問題，然後鎖定螢幕控制增加了上一首/下一首功能，其他部分應該全部沒動，所以我覺得很怪
2.2(99)  最低ios限制我設定15.0
2.2(100) 最低ios限制我設定14.5

最低ios限制會決定函式庫能用多新的產生最終的App，但是理論上應該能裝就不會有問題，目前測試起來也不是這個問題，所以還要找，等我想到哪邊有可能，再請你幫忙測試，真的麻煩你了，謝謝

**Comment by jonsonnee** [comment]
Andy你好

我才覺得不好意思
讓你這兩天一直在忙著測試

如果這只是我的個案
我覺得沒關係
只是多按一次按鍵就OK了

未來有任何進展
我會繼續協助測試的

讓你花那麼多時間
再次感謝您


從我的iPhone傳送

**Comment by totality-of-life** [comment]
有空幫忙我實驗2.2(101)版本看看，不急，這問題其實讓我很好奇

**Comment by jonsonnee** [comment]
Sorry  這個版本一樣不行喔

從我的iPhone傳送

**Comment by totality-of-life** [comment]
有空幫忙我實驗2.2(102)版本看看，一樣不急

**Comment by jonsonnee** [comment]
好棒棒
OK了
謝謝您🙏
辛苦了

從我的iPhone傳送

**Comment by totality-of-life** [comment]
有空幫忙我實驗2.2(103)版本看看，一樣不急。
剛剛沒事的版本是把控制面板的功能先拿掉，這次經過一點點檢查，確定讀到一首曲子才設定面板，應該就會解決你遇到的問題了。

**Comment by jonsonnee** [comment]
103版 不行喔
謝謝

從我的iPhone傳送

**Comment by totality-of-life** [comment]
104版 今晚的最後一次嘗試，晚安

**Comment by jonsonnee** [comment]
早安

104版 OK喔

謝謝您

從我的iPhone傳送
