### ISSUE TITLE
2.4版排序按鈕可新增文字說明

### ISSUE THREAD

**Issue by Lotusho** [totality-of-life/testing-ios#29]
2.4版新增排序功能，畫面只有一個箭頭，比較不容易理解箭頭的功用，建議可新增文字說明，例如在箭頭前加「排序」，參考看看。
謝謝Andy~👍

**Comment by totality-of-life** [comment]
謝謝，我覺得應該不錯，來試試看

**Comment by totality-of-life** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-02-09 at 21 06 19](https://user-images.githubusercontent.com/72474898/153207227-d830f48f-f5e7-40c6-ad78-6a534a66e943.png)
這樣大家覺得清楚嗎？ 有其他建議也歡迎討論，感謝

**Comment by yoshi119** [comment]
Ver.：2.4(116)測試回報
Device：iPhone 7
IOS：14.6
**### 測試結果：雲端未出現排序功能**
![IMG_7353](https://user-images.githubusercontent.com/54445562/153315855-0b9c05a8-7fb5-45e3-a765-0157d8f252a0.PNG)

**Comment by totality-of-life** [comment]
> Ver.：2.4(116)測試回報 Device：iPhone 7 IOS：14.6 **### 測試結果：雲端未出現排序功能**

感謝！！
我現在的寫法是比較新的做法，居然在ios 14.X不會出現最底下的bar，這算是Apple本身的bug，15.0之後都是正常的，不過大部分朋友都還是14.X，還是要找一個都可以支援的寫法。

Andy

**Comment by totality-of-life** [comment]
把按鈕改到上面，這樣應該沒問題了

![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-02-10 at 14 54 33](https://user-images.githubusercontent.com/72474898/153353518-3ea7a739-deb3-4ef6-98c4-d12f4708f7c1.png)

**Comment by Julian8153** [comment]
1.排序使用正常，放置在上方也一目瞭然。
2.清理頁面有清楚顯示音檔時間長度。
iPhone XR 
iOS 15.1
謝謝～辛苦了☺️

**Comment by yoshi119** [comment]
Ver.：2.4(117)測試回報
Device：iPhone 7
IOS：14.6
測試結果：排序功能正常
![IMG_7354](https://user-images.githubusercontent.com/54445562/153521329-be035e3e-76b5-4fe5-a67e-253ea3c90238.PNG)
