### ISSUE TITLE
2.0(76) 閃退問題

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-ios#3]
我自己發生過一次，還沒找到什麼原因造成，大家如果有發生也可以描述一下怎樣操作會閃退

ps. 如果手機遇到很嚴重閃退，影響自己聽共修，也可以先回去裝App store的版本，等下一個測試版再加入，都沒有關係，主要是有bug回報到github，讓我們可以有線索找到問題點，這樣就有很大的幫忙

--
iPhone SE2 
iOS 14.7.1

**Comment by Kila888** [comment]
2.0閃退問題，
下載感恩身體的功課時，按下載影片閃退。再次進app繼續下載，下載5、6個影片後又再次閃退。

完整下載感恩身體的功課所有檔案大概閃退5次左右。
播放感恩身體的功課影片04，在0:11秒閃退，播兩次都一樣0:11秒閃退。


iPad Air 4
iOS.14.7.1

**Comment by totality-of-life** [comment]
目前猜測是因為新增了檔案完整性的MD5掃描檢查，這在打開app的時候會觸發，其實只要做完一次，只是檔案多的時候，做完一次要很久，所以變成重複開關app的時候，可能有兩個以上的掃描在同時重複跑，他們互相在打架，寫入了同個檔案位置，造成閃退。

只要第一次開啟app，放著一陣子，讓他完整跑完掃描一次就好，暫時先不要重複開啟app，避免觸發第二個掃描重複跑。
未來就可以隨便操作，因為每次新下載檔案其實只需要掃描一個檔案，其實非常快，就不會遇到這個問題。

這在下次的版本會修好

**Comment by alfredoyang** [comment]
It still happens after rebooting my device. It took about 15~20 seconds before it closed.

iPhone 12mini
IOS 14.7.1

**Comment by Joeychausc** [comment]
Problem seem resolved with V2(77).

Ios 14.7.1
Iphone XS Max
