### ISSUE TITLE
TestFlight無法登入？

### ISSUE THREAD

**Issue by mingzhen2020** [totality-of-life/testing-ios#4]
中午重新下載app，但一直是「沒有可測試的app」。請問如何處理？謝謝![image](https://user-images.githubusercontent.com/64645472/132624704-7460bf8f-4810-4225-b16a-dca0eb5f3ffa.png)

**Comment by totality-of-life** [comment]
你有回信給我Apple ID嗎？

Andy

**Comment by mingzhen2020** [comment]
補充：
1. 手機型號：iphone7
2. 作業系統版本:iOS
3. 怎樣操作發生問題的：如上

**Comment by mingzhen2020** [comment]
> 你有回信給我Apple ID嗎？
>YES!

**Comment by mingzhen2020** [comment]
> 你有回信給我Apple ID嗎？
Yes!
huangcti@gmail.com

**Comment by totality-of-life** [comment]
apple會發一個邀請到apple id那個email裡面，請看看有沒有，沒有再跟我說，我可以按重寄

**Comment by mingzhen2020** [comment]
> apple會發一個邀請到apple id那個email裡面，請看看有沒有，沒有再跟我說，我可以按重寄

沒有收到信，麻煩重寄，謝謝。

**Comment by mingzhen2020** [comment]
收到了。也完成登入。謝謝
