### ISSUE TITLE
需要兌換碼進入測試版

### ISSUE THREAD

**Issue by Mina5632** [totality-of-life/testing-ios#5]
![7A2EC7C2-D6E1-43A8-BD30-D980755364D1](https://user-images.githubusercontent.com/90369794/132626945-0efb2b49-d4b1-4b6f-988a-3467d5009cc2.png)

**Comment by totality-of-life** [comment]
請問你有回信告訴我apple id嗎？
因為有隱私問題，你可以直接寄信跟我說，我看不出來你的email是哪一個。
可以檢查一下有沒有打錯apple id


我們是採用apple id加入testers group這個模式，加入以後每次更新測試版都會自動通知
兌換碼是一次性的，每次更新都要重新給，跟我們用的不一樣，我們不會用到兌換碼

**Comment by Mina5632** [comment]
Apple ***@***.***

totality ***@***.***>於 2021年9月9日 週四，下午1:31寫道：

**Comment by totality-of-life** [comment]
apple會發一個邀請到apple id那個email裡面，請看看有沒有，沒有再跟我說，我可以按重寄

**Comment by yei1003** [comment]
發生此情況的朋友，要回去Apple iCloud 信箱收Andy寄給你的邀請信，打開連結就可以了
