### ISSUE TITLE
「感恩身體功課」內影片無法在後台自動播放

### ISSUE THREAD

**Issue by tinaho328** [totality-of-life/testing-ios#6]
剛下載了感恩身體的功課裡面的第一個影片：結構調整的重點01， 把app向上拉，想縮去後台播放，結果無法在後台繼續播出聲音。 因為共修音頻那邊的音頻是可以繼續後台播放，手機仍可以滑看其他app來使用，不影響聲音播放。 所以運動影片這一塊，會打算也設置為可以也能在後台播放聲音嗎？

謝謝！

**Comment by totality-of-life** [comment]
你的意思是要影片當作音樂來聽，我當初沒有想到這個應用，這個等到2.1版我們再來考慮看看，謝謝

**Comment by tinaho328** [comment]
對啊，有時候在運動的時候 就不會專注看畫面了，可能會閉目跟隨運動引導，就想要聽聲音引導。
可是手機隔一段時間就會關閉螢幕，一關閉螢幕後，影片就會暫停播放了，手要去點屏幕重新打開， 這樣就沒法很順暢的邊「享受」邊做運動了。
除非大家都特地去把手機屏幕設為永不關閉屏幕（不過這樣蠻耗電的）謝謝你的努力🙏🏻

**Comment by totality-of-life** [comment]
影片跟音檔對於iOS來說的處理其實不一樣，其實主要是省電，Apple其實想說你螢幕關起來就沒辦法看影片了，所以也會把影片播放器關掉減少耗電，要特別處理過，強迫他播放。
妳回報的使用情況相當合理，等這次2.0兩邊版本都穩定下來，上架以後，比較有時間會來處理。

**Comment by totality-of-life** [comment]
我剛剛稍微查了一下怎麼做，不是短時間會做好的，所以這次應該沒辦法，我也不想有太多變動影響穩定性，不過別擔心我們會每次不斷把App變更好的，一步一步來。

**Comment by tinaho328** [comment]
沒關係！ 不急，哈哈慢慢來，都是在最好的安排上

**Comment by CrystaKu** [comment]
不過，我在看影片跟音檔完全一樣，都可以離開這個App繼續使用手機，螢幕關了也繼續有聲音喔！

iPhone 7 Plus
iOS 14.7.1

**Comment by tinaho328** [comment]
> 不過，我在看影片跟音檔完全一樣，都可以離開這個App繼續使用手機，螢幕關了也繼續有聲音喔！

您是哪款型號iPhone噢？

**Comment by CrystaKu** [comment]
> > 不過，我在看影片跟音檔完全一樣，都可以離開這個App繼續使用手機，螢幕關了也繼續有聲音喔！
> 
> iPhone 7 Plus
iOS 14.7.1
> 
> 您是哪款型號iPhone噢？

**Comment by tinaho328** [comment]
我是Iphone 11 pro max, 版本： ios 14.7.1 
無法影片後台播放🤣 感覺是機型的問題

**Comment by CrystaKu** [comment]
我剛剛測試幾次後發現～
如果只要用「聽」，不停留在此App，要使用手機或關螢幕用聽的～
請離開「已下載」，點選「雲端」，再離開此App即可喔！

**Comment by tinaho328** [comment]
> 我剛剛測試幾次後發現～
> 如果只要用「聽」，不停留在此App，要使用手機或關螢幕用聽的～
> 請離開「已下載」，點選「雲端」，再離開此App即可喔！

欸 真的！ 離開「已下載」，點選「雲端」，再離開app 就真的可以後台播放影片了。可以正常使用其他app和手機，並且關螢幕也會繼續播放👍🏻 
太棒了妳

**Comment by totality-of-life** [comment]
天啊，你們好厲害。你們避免掉了Apple本身去對於播放器的省電檢查，我剛剛也實驗出來了，就讓播放器在關螢幕的時候沒有顯示，所以關閉的時候，iOS就沒有觸發關閉這件事。我笑得好開心。這做法真的相當神奇，其實你們發現了一個iOS本身的漏洞

**Comment by yei1003** [comment]
> 我剛剛測試幾次後發現～
> 如果只要用「聽」，不停留在此App，要使用手機或關螢幕用聽的～
> 請離開「已下載」，點選「雲端」，再離開此App即可喔！

iphone8
14.7
背景播放測試ok

**Comment by Kila888** [comment]
> > 我剛剛測試幾次後發現～
> > 如果只要用「聽」，不停留在此App，要使用手機或關螢幕用聽的～
> > 請離開「已下載」，點選「雲端」，再離開此App即可喔！
> 
> iphone8
> 14.7
> 背景播放測試ok

哇!真的耶 謝謝

**Comment by totality-of-life** [comment]
找到方法做好了，基本上只要讓關掉螢幕的瞬間，iOS沒有顯示影片播放，他就不會去關閉。
目前還有小問題，就是全螢幕播放的時候，第一次關閉螢幕還是會被中斷，重新按play，之後關閉螢幕就可以背景播放了，目前原因不明
這都是Apple想幫手機省電的設計，現在應該暫時可以滿足大部分需求，未來有機會再來看怎麼改善

**Comment by Julian8153** [comment]
可以當背景播放但無法按暫停，只能調大小聲哦。
iPhone XR 
iOS 14.7.1

**Comment by newlix** [comment]
> 可以當背景播放但無法按暫停，只能調大小聲哦。
> iPhone XR
> iOS 14.7.1

謝謝回報，如果是播放影片，那這是正常的。
那一個lockscreen的面板是iOS內建播放器本身去放的，告訴你他在運作，apple預期你要真的進去APP用那個播放器的控制項才能操作它。我目前沒有找到方法可以從外面控制，之後可以再找找。
播放音檔的部分，應該是可以正常控制的，

**Comment by totality-of-life** [comment]
影片的話，這樣是正常的

**Comment by totality-of-life** [comment]
ios 15 增加了這項支援的設定，可是我們為了支援最多手機，目前不會強制大家升級到ios15
https://developer.apple.com/documentation/avfoundation/avplayer/3787548-audiovisualbackgroundplaybackpol
