### ISSUE TITLE
持續閃退

### ISSUE THREAD

**Issue by Mina5632** [totality-of-life/testing-ios#7]
APP內五個課程皆呈現閃退狀態中

**Comment by totality-of-life** [comment]
可以先從TestFlight更新成最新版2.0(77)再試試看，謝謝

**Comment by Kila888** [comment]
2.0(77)。
播放音檔和影片目前沒閃退。能播完一則影片沒閃退。

iPad Air 4
iOS 14.7.1

**Comment by coolbil** [comment]
2.0(77) 
播放影片和音樂皆正常，還有背景撥放 讚!

iPhone 7
iOS 14.7.1
