### ISSUE TITLE
運動練習的影片畫面建議：增加展開為全屏播放功能

### ISSUE THREAD

**Issue by tinaho328** [totality-of-life/testing-ios#8]
剛看結構調整的影片， 發現影片畫面沒有可以按展開為全屏播放的選項，如果可以新增功能，讓讀者可以按全屏影片看會比較方便（好像youtude 的影片可以點開變全屏播放那樣），現在的畫面有點小，老人家或者視力不好的朋友會比較吃力🙏🏻

![CD6E922F-8AB4-489D-AF5A-93D94586F781](https://user-images.githubusercontent.com/90365458/132635203-64de1ee5-37db-4d74-9534-34460dbebecb.png)

**Comment by totality-of-life** [comment]
底下正中間的按鈕有這個功能

**Comment by totality-of-life** [comment]
順便說一下，影片播放器內部的按鈕是iOS內建提供的，沒有辦法更改，如果對於其他按鈕應該怎麼放的建議，要從外面來思考。
感謝每一個回饋
