### ISSUE TITLE
有Apple TV 的朋友請幫忙測試可以在上面播放嗎？

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-ios#9]

**Comment by Mina5632** [comment]
正常

**Comment by Mina5632** [comment]
> 正常播放

**Comment by sinclair0904** [comment]
我的apple tv中的testflight跟我說需要邀請碼...才可以istall 全部生命app，請問該如何取得邀請碼....P.S我的 ipad pro就沒這問題 好奇怪....

**Comment by newlix** [comment]
> 我的apple tv中的testflight跟我說需要邀請碼...才可以istall 全部生命app，請問該如何取得邀請碼....P.S我的 ipad pro就沒這問題 好奇怪....

是用iPhone或ipad透過airplay輸出到Apple TV，沒有寫可以直接在apple TV跑的App吧？

**Comment by sinclair0904** [comment]
噗噗  好低 感恩...airplay播放正常(iphone 11 & ipad pro 二代 ios 14.7.1).....
